driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform

platforms:
  - name: gcp

suites:
  - name: default-vpc
    driver:
      root_module_directory: test/fixtures/default-vpc
    verifier:
      color: false
      systems:
        - name: default-vpc
          backend: gcp
          attrs_outputs:
            gcp_project_id: project_id
          controls:
            - attributes
            - gcp-resources
            - cis-gcp-3.6-networking
            - cis-gcp-3.7-networking
